name: top_football_team
description: Ios and Android app to display the most recent best performing team

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  clock: ^1.1.0
  intl: ^0.17.0
  provider: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  mockito: ^5.1.0
  build_runner: ^2.1.8
  fake_async: ^1.2.0

flutter:

  uses-material-design: true
